### ISSUE TITLE
no 1.20.1 version?

### ISSUE THREAD

**Issue by Aceplante2** [Nyancatpig/Alexs-Delight-1.19.2#7] opened 2023-12-31 21:29 UTC
there should be

**Comment by Nyancatpig** [comment] 2023-12-31 23:08
this is not a bug
i’ll get to porting it when i get to porting it
this issue post was certainly unnecessary 

also, by the looks of the dozens of issues you open on mod repos, you're a homophobic bigot
i’ve now decided that this mod will not be updated to 1.20.1, and i will be instead focusing on 1.13 only, exclusively on the rift modloader

**Comment by Aceplante2** [comment] 2024-01-01 16:25
In some cases, a mod author forgets about or moves on from a mod and does not have plans to update it, until he sees it is requested? I figured this was the best place to post a request for a new version.

Second, I'm not sure what other repos have to do with anything. If you have a bug with your mod, or in this case a feature request, would you not want to know about it just becuase you disagree with my moral beliefs? I dont know what comments you're referring to specifically but I assume youre referring to ones where I expressed dissupport for the lgbt. As I clarified though in these other comments, I do not hate them as people, as everyone is entitled to their own choices, I simply do not agree or support them. Never have, dont plan to, and see no reason to have that in my silly block game where we go to avoid all that. If disagreeing makes me "homophobic", so be it. But again, what does that have to do with this mod?

Nor have I ever heard of a rift modloader, and 1.13 seems like an odd choice, or perhaps this was irony.

**Comment by Nyancatpig** [comment] 2024-01-01 23:18
no, if someone has the request to port the mod to the latest version i don’t want to know about it
everyone and their mother asks for ports

being lgbt isnt a choice, not supporting them makes you a turd, representation is important, etc etc
homophobes aren’t allowed to post suggestions here


please check out the hit modpack Raspberry Flavoured, a fun time for the whole family!

**Closed by Nyancatpig** 2024-01-01 23:18 UTC
